### ISSUE TITLE
colour property Not working properly with nested elements

### ISSUE THREAD

**Issue by Parth589** [ehsan-shv/react-creative-cursor#8]
I have two nested elements. both have different data-cursor-color prop. when cursor gets into parent, it works fine.
![Screenshot_20230711_110318](https://github.com/ehsan-shv/react-creative-cursor/assets/73070478/19839c13-cb8b-49bf-85c9-f1303aaf5155)

when i put cursor into the child element, it also works fine.
![Screenshot_20230711_110331](https://github.com/ehsan-shv/react-creative-cursor/assets/73070478/0116586a-8136-4079-8042-13b3baf4c497)

but the problem happens when i get the cursor out of the child element, the cursor does not change color for the parent element
![Screenshot_20230711_110342](https://github.com/ehsan-shv/react-creative-cursor/assets/73070478/894f08d3-a5f2-4c50-9af5-fa1d8ae290c4)

am i doing something wrong? or it's an expected behaviour?

**Comment by ehsan-shv** [comment]
Hi! It doesn't work with nested elements.
